### ISSUE TITLE
mate-volume-control-applet crashes when changing device profiles with mate-volume-control

### ISSUE THREAD

**Issue by Asta1986** [mate-desktop/mate-media#104]
#### Expected behaviour
Using mate-volume-control or pavucontrol hardware device profiles can be switched without effect on the volume applet.

#### Actual behaviour
Sometimes when using mate-volume-control (or pavucontrol) to switch device profiles (in the 'Hardware' tab) mate-volume-control-applet crashes.

#### Steps to reproduce the behaviour
Open mate-volume-control and change device profiles several times.
In my case it occurs with one USB headset and one onboard soundcard, although I'm not sure whether having more than one device has anything to do.

#### MATE general version
1.19.1

#### Package version
mate-applets-1.19.2-2.fc27.x86_64

#### Linux Distribution
Fedora 27.

#### Link to downstream report of your Distribution
 -

I'll try to get a stacktrace and upload it.

**Comment by Asta1986** [comment]
I was able to reproduce it again today with abrtd running but it didn't save a trace. If there is another way let me know.

**Comment by raveit65** [comment]
Oh, there is no trace inside /var/spool/abrt/id-of-your-crash/  ?
A backtrace can be generated with executing 'abrt-action-analyze-ccpp-local' inside this folder.

Other solution is to start mate-volume-control-applet with gdb, see http://fedoraproject.org/wiki/StackTraces#gdb for instructions.
Don't forget to kill the running applet first.

Btw. i can switch the sound device in the **output tab** of mate-volume-control without a crash in fedora 26, and after reloading a video inside parole media-player the new device is used.
Tested with on-board device from my mobo and hdmi-device from monitor.
Note, i am using MATE-1.19 here with f26, same as in f27.

**Comment by Asta1986** [comment]
I think I was able to get it with gdb. I uploaded the whole output just in case (not only the part after issuing 'thread apply all bt full') to https://gist.github.com/Asta1986/86ee184567fb1d08dc56acaeccdd6a81 .
Regards.

**Comment by raveit65** [comment]
Can you please install missing debuginfo packages before you type 'run' in gdb, see gdb output?

```
Reading symbols from mate-volume-control-applet...Reading symbols from /home/asta666/mate-volume-control-applet...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Missing separate debuginfos, use: dnf debuginfo-install mate-media-1.19.1-1.fc27.x86_64
```

**Comment by Asta1986** [comment]
OK I did it and this is the output afterwards https://gist.github.com/Asta1986/d6aea85b1043dc44bb80346627beef92
At some point I still got 
"Missing separate debuginfos, use: dnf debuginfo-install gtk3-3.22.26-1.fc27.x86_64 pcre2-10.30-3.fc27.x86_64" 
although that package is installed.

**Comment by Asta1986** [comment]
When I run the dnf command I get the following:

> gtk3-debuginfo-3.22.26-2.fc27.x86_64 is already installed, skipping.
Package pcre2-debuginfo-10.30-4.fc27.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.

The release number of the ones installed is higher than the ones in the warning but I don't see any other versions available in the repositories.

> ~$ dnf --showduplicates list gtk3-debuginfo 
Last metadata expiration check: 8 days, 12:58:09 ago on Wed 03 Jan 2018 08:30:01 PM -03.
Installed Packages
gtk3-debuginfo.x86_64                                3.22.26-2.fc27                                @updates-debuginfo
Available Packages
gtk3-debuginfo.x86_64                                3.22.26-2.fc27                                @updates-debuginfo

**Comment by raveit65** [comment]
Ok, but it looks like that it is already reported at rhbz with a similar stacktrace.
https://bugzilla.redhat.com/show_bug.cgi?id=1523656
Sadly, it crashes at a gtk3 function in both stacktraces, imo.
```
#4  0x00007fe70030eb46 in gtk_widget_get_frame_clock (widget=0x55d7a141eb90) at gtkwidget.c:5813
        window = <optimized out>
#5  0x00007fe70031cada in gtk_widget_realize (widget=widget@entry=0x55d7a141eb90) at gtkwidget.c:5483
        priv = 0x55d7a141eaa0
        region = <optimized out>
        __func__ = "gtk_widget_realize"
```
So i am not sure what we can do here.
And you said pavucontrol would be crash too, right?

**Comment by Asta1986** [comment]
Yes, it also sometimes crashes when changing device profiles with pavucontrol (in the "Configuration" tab).

**Comment by monsta** [comment]
Crashes at the same place as https://github.com/mate-desktop/mate-media/issues/89, the backtrace is identical.

**Comment by geckolinux** [comment]
Hi there, I'm not sure if I need to create a new report, but I suspect that mine is the same cause. My mate-volume-control-applet crashes multiple times per day. The crashes don't directly correlate with changing device profiles, and they feel totally random. But I do frequently connect and disconnect different Bluetooth headphones and I switch between them and the built-in Intel audio, both speakers and wired earphones. As for the Bluetooth devices, I only use A2DP and I don't switch the device profile, but maybe it's briefly connecting as HSP and then switching automatically to A2DP. At any rate, it's both frustratingly random and frustratingly frequent at the same time. This is with all the latest Mate components (and latest everything else) on openSUSE Tumbleweed.

**Comment by raveit65** [comment]
Same like https://github.com/mate-desktop/mate-media/issues/201
which got a proper and newer stacktrace.
So closing this report in favor of the other one.
