### ISSUE TITLE
Porting mate-volume-applet to AFAIK

### ISSUE THREAD

**Issue by ghostplant** [mate-desktop/mate-media#107]
Porting mate-volume-applet from Xembed to AFAIK, and it is needed in the future.

**Comment by raveit65** [comment]
Already done. We have a panel applet now.

**Comment by ghostplant** [comment]
Great! Will it be in Ubuntu 24.04?

**Comment by raveit65** [comment]
I am using fedora.....we us it since fedora 30 :)
Ask ubuntu....

**Comment by lukefromdc** [comment]
The panel applet also works in both x11 and wayland, we also retained the status icon as an option for compatability with older panel setups users might not want to reconfigure etc.
