### ISSUE TITLE
mate volume control applet

### ISSUE THREAD

**Issue by marcscama** [mate-desktop/mate-media#113]
===================================================================
 GDB Log                                                           
===================================================================

warning: core file may not match specified executable file.
[New LWP 1502]
[New LWP 1529]
[New LWP 1528]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `mate-volume-control-applet'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f5bb71e6fc0 (LWP 1502))]

===================================================================
 GDB Backtrace                                                     
===================================================================

warning: core file may not match specified executable file.
[New LWP 1502]
[New LWP 1529]
[New LWP 1528]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `mate-volume-control-applet'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f5bb71e6fc0 (LWP 1502))]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f5bb4b29801 in __GI_abort () at abort.c:79
#2  0x00007f5bb516bfa5 in g_assertion_message () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f5bb516c00a in g_assertion_message_expr () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f5bb62898f6 in gtk_widget_get_frame_clock () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007f5bb629757a in gtk_widget_realize () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007f5bb6297798 in gtk_widget_map () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007f5bb60300cc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007f5bb60786cf in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007f5bb541f0b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007f5bb543a6df in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007f5bb543ae0f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007f5bb6297742 in gtk_widget_map () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007f5bb62ad6cf in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007f5bb541f1a6 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007f5bb543a6df in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007f5bb543ae0f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007f5bb6297742 in gtk_widget_map () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007f5bb62a534d in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007f5bb541ef6d in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007f5bb5431e0e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007f5bb543a3f5 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007f5bb543ae0f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007f5bb6291696 in gtk_widget_show () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007f5bb624830d in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007f5bb6248d5f in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007f5bb5c46080 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#27 0x00007f5bb5145b73 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f5bb51450f5 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007f5bb51454c0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007f5bb51457d2 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007f5bb613f385 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x0000560446c3aa45 in main ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================

warning: core file may not match specified executable file.
[New LWP 1502]
[New LWP 1529]
[New LWP 1528]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `mate-volume-control-applet'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f5bb71e6fc0 (LWP 1502))]

Thread 3 (Thread 0x7f5bab750700 (LWP 1528)):
#0  0x00007f5bb4bfdbf9 in __GI___poll (fds=0x560448b18450, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f5bb5145439 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f5bb514554c in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f5bb5145591 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f5bb516ce05 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f5bb4ee16db in start_thread (arg=0x7f5bab750700) at pthread_create.c:463
        pd = 0x7f5bab750700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140031695324928, -7920512980908537131, 140031695322240, 0, 94576399150960, 140732432809776, 7828374911383210709, 7828319056839543509}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f5bb4c0a88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f5baaf4f700 (LWP 1529)):
#0  0x00007f5bb4bfdbf9 in __GI___poll (fds=0x560448b2b870, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f5bb5145439 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f5bb51457d2 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f5bb594ae76 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f5bb516ce05 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f5bb4ee16db in start_thread (arg=0x7f5baaf4f700) at pthread_create.c:463
        pd = 0x7f5baaf4f700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140031686932224, -7920512980908537131, 140031686929536, 0, 94576399151184, 140732432810160, 7828376010357967573, 7828319056839543509}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f5bb4c0a88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f5bb71e6fc0 (LWP 1502)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
        set = {__val = {0, 94576401028909, 94576401029100, 94576401028800, 94576401029100, 0, 2064, 124, 140031875728525, 140732432806960, 140031854201920, 140031850698712, 570470039552, 2048, 343597383680, 7}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007f5bb4b29801 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xfefc, sa_sigaction = 0xfefc}, sa_mask = {__val = {94576402211904, 0, 140732432806960, 140728898420737, 9055473248090770688, 72057594037927936, 16777216, 7566047373982433280, 140030983012352, 94576402211904, 0, 0, 9055473248090770688, 140031875728525, 94576402211904, 106}}, sa_flags = -1254040096, sa_restorer = 0x7ffed2aa7430}
        sigs = {__val = {32, 0 <repeats 15 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#2  0x00007f5bb516bfa5 in g_assertion_message () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f5bb516c00a in g_assertion_message_expr () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f5bb62898f6 in gtk_widget_get_frame_clock () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#5  0x00007f5bb629757a in gtk_widget_realize () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#6  0x00007f5bb6297798 in gtk_widget_map () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#7  0x00007f5bb60300cc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#8  0x00007f5bb60786cf in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#9  0x00007f5bb541f0b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#10 0x00007f5bb543a6df in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#11 0x00007f5bb543ae0f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#12 0x00007f5bb6297742 in gtk_widget_map () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#13 0x00007f5bb62ad6cf in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#14 0x00007f5bb541f1a6 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#15 0x00007f5bb543a6df in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#16 0x00007f5bb543ae0f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#17 0x00007f5bb6297742 in gtk_widget_map () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#18 0x00007f5bb62a534d in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#19 0x00007f5bb541ef6d in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#20 0x00007f5bb5431e0e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#21 0x00007f5bb543a3f5 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#22 0x00007f5bb543ae0f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#23 0x00007f5bb6291696 in gtk_widget_show () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#24 0x00007f5bb624830d in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#25 0x00007f5bb6248d5f in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#26 0x00007f5bb5c46080 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#27 0x00007f5bb5145b73 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#28 0x00007f5bb51450f5 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#29 0x00007f5bb51454c0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#30 0x00007f5bb51457d2 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#31 0x00007f5bb613f385 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#32 0x0000560446c3aa45 in main ()
No symbol table info available.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f5bb4b29801 in __GI_abort () at abort.c:79
#2  0x00007f5bb516bfa5 in g_assertion_message () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f5bb516c00a in g_assertion_message_expr () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f5bb62898f6 in gtk_widget_get_frame_clock () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007f5bb629757a in gtk_widget_realize () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007f5bb6297798 in gtk_widget_map () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007f5bb60300cc in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007f5bb60786cf in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007f5bb541f0b0 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007f5bb543a6df in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007f5bb543ae0f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007f5bb6297742 in gtk_widget_map () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007f5bb62ad6cf in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007f5bb541f1a6 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007f5bb543a6df in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007f5bb543ae0f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007f5bb6297742 in gtk_widget_map () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007f5bb62a534d in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007f5bb541ef6d in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007f5bb5431e0e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007f5bb543a3f5 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007f5bb543ae0f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007f5bb6291696 in gtk_widget_show () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007f5bb624830d in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007f5bb6248d5f in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007f5bb5c46080 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#27 0x00007f5bb5145b73 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f5bb51450f5 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007f5bb51454c0 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007f5bb51457d2 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007f5bb613f385 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x0000560446c3aa45 in main ()

**Comment by raveit65** [comment]
Template ignored...
.... report ignored.

**Comment by monsta** [comment]
Same backtrace as https://github.com/mate-desktop/mate-media/issues/89
