### ISSUE TITLE
getting sound test to work?

### ISSUE THREAD

**Issue by oz123** [mate-desktop/mate-media#136]
Hi, 
I would really appreciate a clue here.

#### Expected behaviour

The sound test buttons do nothing ...

#### Actual behaviour
A sound "front left" or "front right" should be heard, like with 
```
 speaker-test -Dplug:default -t wav -c 2
```

#### Steps to reproduce the behaviour
![sound-test](https://user-images.githubusercontent.com/1083045/60544156-6e7d6b80-9d18-11e9-9af5-c573b97f41fa.png)

run mate-volume-control go to hardware tab, press Test speakers.

#### MATE general version
mate-1.22.X from Gentoo ebuilds.

#### Package version

 $ equery u mate-media
!!! No USE flags found for mate-extra/mate-media-1.22.1

#### Linux Distribution
 
gentoo

**Comment by oz123** [comment]
Helped myself with some more google foo ...
From arch linux wiki:


Speaker test does not work

For PulseAudio backend, install libcanberra's optional dependency libcanberra-pulse.

**Comment by lukefromdc** [comment]
I have pulseaudio and libcanberra-pulse and can confirm the speaker tests work here.
