### ISSUE TITLE
Volume hotkeys target wrong device

### ISSUE THREAD

**Issue by knochenhans** [mate-desktop/mate-media#141]
#### Expected behaviour
After attaching a usb soundcard the volume hotkeys should point to the attached soundcard if it set as the default audio output device.

#### Actual behaviour
After attaching a usb soundcard the volume hotkeys change the internal soundcard’s volume, not the usb soundcard’s volume (which is set as the default audio output device).

#### Steps to reproduce the behaviour
Attach a usb soundcard, try changing the output volume via volume up/down hotkeys. This problem only occurs from time to time.

#### MATE general version
1.22.1

#### Package version
1.22.1-1

#### Linux Distribution
Arch Linux

Is there any way to manually change what device the volume hotkeys target? That would be a big help already :)

**Comment by lukefromdc** [comment]
That sounds like an issue with pulseaudio not always detecting that the default audio device has changed rather than with anything that is maintained by MATE.

**Comment by knochenhans** [comment]
Audio output works fine though, sound is correctly routed to the newly attached sound device by pulseaudio, but the hotkeys don’t affect it. For example, in mate-volume-control the new device is selected as the current output device under the “Output” tab but the Output volume slider (at the top) doesn’t move when I press the volume hotkeys. It does move though when I choose the internal audio device.

**Comment by lukefromdc** [comment]
OK, at this point I don't know enough about it ti determine whether this
in mate-media or libmatemixer (updating some but not all default sound
card variables), or in an underlying library. Hopefully someone on our team
will know more.

**Comment by vkareh** [comment]
@knochenhans - is it possible for you to test the changes in #142 to see if they fix the issue for you? I don't have a secondary output device to test this with, so I just coded it blindly...

**Comment by raveit65** [comment]
I think i can reproduce the issue when i plugin my usb-headset (soundcard) in a running MATE.
Then both soundcards are activated in mate-volume-control (GUI). but mixer in panel use my main soundblaster soundcard.
When i start my box and the headset is plugged in, than the volume-slider in panel use the headset.
Plug in/out the headset at this point in the running mate session will change the device for the volume-slider in panel immediately.
For some reasons the headset is always the first one in the list of the device- and output-tab of mate-volume-control, and it seems that the volume-slider in panel use always the first one in the list when both are activated.
But we don't have an option here to say that one from 2 or 3 cards is the default.
Why do you think your usb device is the default?

Now testing PR......

**Comment by raveit65** [comment]
Hmm,
now i know what you mean with default, which is that one which is selected in the output tab.
But mate-volume-control recognised this setting for me, when i plug in my usb headset.
And the volume-slider use my headset after it is plugged in.
So, i can't reproduce your problem with fedora 30 + MATE 1.23.x + pulseaudio-12.2-6.fc30.x86_64

**Comment by lukefromdc** [comment]
I've never once seen something like this happen on say, setting up HDMI sound and then setting back to my normal soundcard. Similarly, the laptop has no working internal sound, can use a USB soundcard or external HDMI sound, and whichever one is in use the volume control controlled the last time I had to play with that. Thus, I have never been able to duplicate this

**Comment by lukefromdc** [comment]
I just tested this with the desktop, toggling between the HDMI and soundcard outputs with the applet in the panel (not the older volume control tray icon) , and finally DID get this issue. Turned out though that what it took to get the new sound device recognized by the hotkeys was to restart mate-settings-daemon, both with and without https://github.com/mate-desktop/mate-media/pull/142
