### ISSUE TITLE
Volume control applet changes volume to 100% when a notification occurs

### ISSUE THREAD

**Issue by martinvonwittich** [mate-desktop/mate-media#152]
#### Expected behaviour

1. Opening the volume applet and changing the volume by dragging the slider with the mouse should not set the volume to 100% when a notification occurs.

#### Actual behaviour

1. Volume is set to 100% :(

#### Steps to reproduce the behaviour

1. Run the following command in the terminal to trigger a notification in 5 seconds:

	```
	sleep 5; notify-send foo
	```

1. Open the volume applet and click and drag the slider. Keep the mouse button down.

1. Wait for the notification ot occur, and notice that the volume slider jumps to 100%.

#### MATE general version

Not sure how to determine this. `mate-about` says MATE Desktop Environment 1.20.1

#### Package version

```
martin@dogmeat ~ % dpkg -l | grep mate-media
ii  mate-media                                 1.20.0-1                                            amd64        MATE media utilities
ii  mate-media-common                          1.20.0-1                                            all          MATE media utilities (common files)
```

#### Linux Distribution

```
martin@dogmeat ~ % lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

**Comment by martinvonwittich** [comment]
I've made a video to illustrate the issue: https://imgur.com/a/JW6A7lj

**Comment by lukefromdc** [comment]
I was unable to duplicate this (following your exact instructions) with current mate-media 1.23.0 from git master. I tested both the status icon and the newer panel applet and neither one jumped the volume when the notification came up with the mouse button still down on dragging the slider

**Comment by martinvonwittich** [comment]
@lukefromdc thanks for attempting to reproduce it! If this is already fixed, I'll just wait for the next Ubuntu LTS release.
