### ISSUE TITLE
Volume Output Increases Only When Sound Preferences App Open and Input Tab Selected

### ISSUE THREAD

**Issue by westcoastsuccess** [mate-desktop/mate-media#172]
#### Expected behaviour
I expect volume level to remain consistent whether mate-volume-control is open or closed, and regardless of which tab is selected in mate-volume-control. I expect the volume of other, non-computer sound sources (i.e. streamed audio to shared speakers) to be unaffected by mate-volume-control status.

#### Actual behaviour
Volume of connected speakers is *very* low for non-computer sources. Opening mate-volume-control and selecting the Input tab causes volume of speakers to increase significantly for audio streamed from another (non-computer) source. However, selecting any other tab in the mate-volume-control app (Sound Effects, Hardware, Output, Applications) causes the sound to reduce to previous levels after a delay of perhaps 5 seconds. Selecting the Input tab again causes the sound to increase significantly, and immediately.

Closing the app similarly causes the volume to decrease significantly after a delay of perhaps 5 seconds.

Re-opening the app to the Input tab again immediately increases the volume. Switching to any other tab in the app again causes the volume to vastly diminish after about a 5 second delay.

The sound source is music streamed to a Chromecast audio which shares the speakers with the computer affected by this issue.

The suddenly increased volume issue also manifests if music is being streamed from a non-computer source and a website initiates audio output - the streamed music's volume immediately and significantly increases until the page is closed, after which volume decreases after about 5 seconds.

As a workaround, I leave the app permanently open on the desktop, with the Input tab selected, to ensure consistent (and reasonable) volume.

Debug info (via "mate-volume-control -d") is uninformative - there is nothing reported in the console when these volume changes occur (either when volume increases, or subsequently decreases). I'm happy to share debug output.

Perhaps Linux or Pulseaudio or Mate tries to do some dynamic audio muting which might somehow be affecting downstream audio (guessing by virtue of website audio acting to increase downstream volume)?

The input to my speakers is a Y splitter, one side of which is connected to the computer at issue, the other connected to a Chromecast Audio device. The issue described above, occuring on the computer on one side of the "Y" connection, affects audio streaming from the other side of the "Y".

Identical behaviour manifests when opening Pulseaudio volume control (volume instantly increases; decreases again 
about 5 seconds after closing app), so perhaps this bug is further upstream?

Here's an example:

[Mate Volume Control Issue Example.mp3.zip](https://github.com/mate-desktop/mate-media/files/5898652/Mate.Volume.Control.Issue.Example.mp3.zip)

#### Steps to reproduce the behaviour
Stream audio to speakers via Chromecast Audio, find volume extremely low even when speakers are at maximum volume. Open mate-volume-control and select Input tab. Volume instantly increases substantially. Navigate to any other tab in mate-volume-control, or close the mate-volume-control app. Volume decreases significantly after a delay of about 5 seconds. This happens each time, without exception.

#### MATE general version
1.24.0, but this has been occurring for a long time (measured in years), and probably across multiple versions.

#### Package version
mate-volume-control 1.24.0

#### Linux Distribution
Linux Mint 20.1

#### Link to bugreport of your Distribution (requirement)
Distribution suggests reporting directly here.

**Comment by raveit65** [comment]
> Distribution suggests reporting directly here.

Distribution forgot to pay donation to do their work.

Ignoring.......

**Comment by westcoastsuccess** [comment]
Not sure I understand your comment, but if you're suggesting there's a better, more suitable place to report this, can you please point me in that direction?

**Comment by lukefromdc** [comment]
Might be.some.kind of issue with the hardware's interaction with the Y splitter. The computer's soundcard/chip (if analog) could be siphoning off sound signal on the cable. Hardware, kernel, or userspace software all could potentially modify this behavior.

There are sound technical reasons this sort of config is rarely used in audio, and why analog mixers always isolate sources from.each other.

**Comment by westcoastsuccess** [comment]
Thanks - appreciate the reply.

I didn't realize it was possible for one side of that chain to affect the other.

I'll explore some alternative routing for the sound.

**Comment by lukefromdc** [comment]
In the days before I was messing with computers I actually built two guitar amps and experimented with mixers, so that is from firsthand knowledge. Even the best digital soundcard's analog outputs in the end work on the same basic principles as those on an analog mixer, radio, tape player, etc.

**Comment by westcoastsuccess** [comment]
Since your initial comment I've been further researching along those lines and learning lots about exactly what you describe. Now looking into an outboard mixer to separate the signals.

Thanks again for pointing me in the right direction - much appreciated!
