### ISSUE TITLE
Invalid icon name in mate-volume-control.desktop

### ISSUE THREAD

**Issue by luigifab** [mate-desktop/mate-media#174]
There is a translation for an "Icon", so the icon doesn't work for french desktop.

![image](https://user-images.githubusercontent.com/31816829/122683334-d0358980-d1fe-11eb-865d-427e29f6d80f.png)

#### MATE general version

1.24.1

#### Package version

1.24.1-1 (https://packages.debian.org/bullseye/mate-media)

#### Linux Distribution

Debian Testing

#### Link to bugreport of your Distribution (requirement)

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990105

**Comment by raveit65** [comment]
I am still wondering why this is a problem in debian. Same package version in official fedora (f34)
```
[rave@f32-test ~]$ su
Mot de passe : 
[root@f32-test rave]# rpm -qa mate-media
mate-media-1.24.1-2.fc34.x86_64
[root@f32-test rave]# cat /usr/share/applications/mate-volume-control.desktop 
[Desktop Entry]
Name[af]=Klank
Name[am]=ድምፅ 

<cut>

Name[zh_CN]=音效
Name[zh_HK]=聲音
Name[zh_TW]=聲音
Name[zu]=Umsindo
Name=Sound
Comment[af]=Verander klankvolume en klankgebeure
Comment[am]=የ ድምፅ መጠን እና የ ድምፅ ሁኔታዎችን መቀየሪያ
Comment[ar]=غيّر شدة الصوت و أصوات الأحداث
Comment[as]=শব্দৰ মাত্ৰা o নিৰ্দিষ্ট ঘটনাৰ সৈতে যুক্ত শব্দ পৰিবৰ্তন কৰক

<cut>

Comment[vi]=Thay đổi âm lượng và âm thanh của sự kiện
Comment[zh_CN]=更改音量以及将声音与事件关联
Comment[zh_HK]=改變音效的音量和音效事件
Comment[zh_TW]=改變音效的音量和音效事件
Comment=Change sound volume and sound events
Exec=mate-volume-control
# Translators: Do NOT translate or transliterate this text (this is an icon file name)!
Icon=multimedia-volume-control
Terminal=false
Type=Application
StartupNotify=true
Categories=AudioVideo;Mixer;Settings;HardwareSettings;
# Translators: Search terms to find this application. Do NOT translate or localize the semicolons! The list MUST also end with a semicolon!
Keywords[ca]=MATE;volum;control;mesclador;ajusts;so;esdeveniments;
Keywords[cs]=MATE;hlasitost;ovládání;ovládat;mixer;směšovač;nastavení;zvuk;události;
Keywords[da]=MATE;volume;control;mixer;settings;sound;events;lydstyrke;kontrol;styring;mikser;indstillinger;opsætning;lyde;hændelser;
Keywords[de]=MATE;Lautstärke;Steuerung;Mixer;Einstellungen;Klang;Ereignisse;
Keywords[es]=MATE;volumen;control;mezclador;ajustes;sonido;eventos;
Keywords[fr]=MATE;volume;contrôle;mixer;paramètres;son;évènements;

<cut>

Keywords=MATE;volume;control;mixer;settings;sound;events;
OnlyShowIn=MATE;
X-MATE-Bugzilla-Bugzilla=MATE
X-MATE-Bugzilla-Product=mate-media
X-MATE-Bugzilla-Component=mate-volume-control
X-MATE-Bugzilla-Version=1.24.1
X-Desktop-File-Install-Version=0.26
[root@f32-test rave]# 
```
As you can see there are no translations for the icon name.

@sunweaver

**Comment by cwendling** [comment]
> I am still wondering why this is a problem in debian. Same package version in official fedora (f34)

I'm wondering how it is *not* a problem in Fedora :)  We really do have a bad translation for this string: https://github.com/mate-desktop/mate-media/blob/1.24/po/fr.po#L46 (since 1b772a77d74e128f482eed8b81343531149e76e0).  Doesn't seem to affect master.

**Comment by raveit65** [comment]
> I'm wondering how it is not a problem in Fedora :)

I guess because of my KungFu :)
https://src.fedoraproject.org/rpms/mate-media/blob/rawhide/f/mate-media.spec#_40
```
desktop-file-install                                                    \
  --delete-original                                               \
  --dir=%{buildroot}%{_datadir}/applications                      \
  %{buildroot}%{_datadir}/applications/mate-volume-control.desktop
```
Anyway, i think the problem was fixed in general with this commit https://github.com/mate-desktop/mate-media/commit/2391307661858d840e3fea36f9f7e4e376b8db35
After this the bad translation was removed from transifex server, but we forgot to re-generate all po files.
In result the culprit string wasn't removed from out git source.
Well, i did that just here https://github.com/mate-desktop/mate-media/commit/8de00386ed3cc42d598d84971fd7fa7fb14d3fb3
@cwendling 
Can you please test if this works for you with 1.24 branch ?
