### ISSUE TITLE
Use symbolic icons for volume control applet

### ISSUE THREAD

**Issue by newhoa** [mate-desktop/mate-media#189]
Using symbolic icons for the applet would make it easier to see in different themes using light or dark panels.

I believe the place to change them is [here](https://github.com/mate-desktop/mate-media/blob/3499a5ffe1ea234e3beedd9615a66470026ae2dc/mate-volume-control/gvc-applet.c#L38-L52) but I'm not familiar with the code and don't know if changes need to be made elsewhere to support symbolic icons.

For reference the standard names are:

```
audio-volume-muted-symbolic
audio-volume-low-symbolic
audio-volume-medium-symbolic
audio-volume-high-symbolic

microphone-sensitivity-muted-symbolic
microphone-sensitivity-low-symbolic
microphone-sensitivity-medium-symbolic
microphone-sensitivity-high-symbolic
```

**Comment by raveit65** [comment]
We do not use symbolic icons. We love a colored world.
