### ISSUE TITLE
Hardware mute key does not unmute

### ISSUE THREAD

**Issue by ysobolev** [mate-desktop/mate-media#19]
The hardware mute key will mute volume in Mate, but it will not unmute. This is present in versions 1.4.2, 1.5, and possibly others.

**Comment by devkid** [comment]
I'm having the exact same problem on Ubuntu 17.10 running MATE 1.18. Neither mate-media-pulse nor mate-settings-daemon-pulse are available in the official repos. Is there any other way to fix that?
