### ISSUE TITLE
wayland: volume slider appear under maximized windows

### ISSUE THREAD

**Issue by Sunderland93** [mate-desktop/mate-media#198]
#### Expected behaviour
Volume slider should appear above any windows

#### Actual behaviour
Volume slider appear under maximized window (e.g. Firefox)

#### Steps to reproduce the behaviour
1) build mate-panel with `--enable-wayland `and `--in-process-applets=all` options
2) build mate media with `--enable-in-process option`
3) add applet to the panel, open any window and maximize it
4) click on volume applet

#### MATE general version
1.26.0

#### Package version
git master

#### Linux Distribution
Debian 12

#### Link to bugreport of your Distribution (requirement)
n/a

**Comment by lukefromdc** [comment]
Confirmed, will look at a fix later today

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-media/pull/199
should fix this, it's literally a one word change. I had gtk-layer-shell set to put the slider on the bottom, this moves it to the top where it belongs
