### ISSUE TITLE
Translation of tab "Applications" brocken

### ISSUE THREAD

**Issue by AhTeeGuu3u** [mate-desktop/mate-media#210]
#### Expected behaviour
![image](https://github.com/mate-desktop/mate-media/assets/5129165/6f91e740-fa98-4721-a363-dd337625ad82)

#### Actual behaviour
![image](https://github.com/mate-desktop/mate-media/assets/5129165/3bb8bc7c-1fa3-4b46-85a1-823c42f98935)

#### Package version
mate-volume-control 1.26.1

#### Linux Distribution
Manjaro

**Comment by AhTeeGuu3u** [comment]
Thanks!

**Comment by raveit65** [comment]
A new release is needed, coming soon....

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-media/releases/tag/v1.26.2
