### ISSUE TITLE
meson.build files are not in released 1.28 tarball generated with distcheck

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-media#213]
#### Expected behaviour
Working releasing with travis-ci

#### Actual behaviour
Meson.build files are missing

#### Steps to reproduce the behaviour

Check released tarball https://github.com/mate-desktop/mate-media/releases/tag/v1.28.0
#### MATE general version

1.28
#### Package version
1.28.0

**Comment by raveit65** [comment]
@mate-desktop/core-team

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-media/commit/2572ea7b984e9abb03aca2d09962261a887eb505
fixed this, tested it and it worked without problems
