### ISSUE TITLE
The sound control disappeared from the panel

### ISSUE THREAD

**Issue by posophe** [mate-desktop/mate-media#42]
Quoted from a post on google+ and a French forum

The sound control disappeared from the panel. I tried to add it from "Add to panel" and there was no sound control. What's the problem? Why it disappeared?  ﻿

*\* (mate-volume-control:2162): WARNING *_: Unable to open display:
*_ (mate-volume-control-applet:2163): WARNING **: Unable to open display :
Try to open   /etc/xdg/autostart/mate-volume-control-applet.desktop

"[...]marked as untrusted"
##

**Comment by jdm15** [comment]
I upgraded from Fedora 20 to 21.  All data and home is on separate partition so I don't loose anything in upgrade.  When I did, the volume control was gone from panel and was not in the list to add back.
mate-volume-control-applet --display=DISPLAY comes back with can not open display. If i create a new user the volume control shows up automatically. I tried to move my home directory, delete my account and re create it then move my home back but that did not work.

**Comment by NiceandGently** [comment]
@jdm15 
Do you see the volume applet in 'mate-session-properties' dialog?

**Comment by tsowa** [comment]
The same in FreeBSD, the sound applet disappeared from the list of available applets.
Some others applets like system monitor are broken. They are visible on the list but when I click 'add' button nothing happens.
Now I don't even have the sound mixer. mate-volume-control displays everything but not the mixer.

I have reverted mate-applets mate-panel and mate-media ports to 1.8 version.

**Comment by raveit65** [comment]
@tsowa 
Please file out a downstream report for it, this looks more like an issue in FreeBSD
@jdm15 
This looks like that an old configuration setting in your home folder causes the issue

**Comment by mratajsky** [comment]
The sound applet is called "applet", but technically it is not a standard panel applet, therefore you will not find it in the applet list. Rather, you start it manually by running the "mate-volume-control-applet" program and this should be done automatically for you at the session start (see the autostart path in the original post). If the sound icon disappears from your tray area, it most likely means that the program does not start automatically, or it crashes, or it couldn't find any sound device. You may of course run it manually from a console and see what happens.

@tsowa, it seems from your report that libmatemixer in FreeBSD ports is not compiled with OSS support (see README), in that case you will get no mixers in mate-volume-control and the applet will not show (it doesn't show if it can't find any sound device in your system). If OSS support is enabled in the port and it still doesn't work, please open a new issue as it is not related to this one.

@jdm15, there really may be some problem related to configuration changes; the display error probably comes from an error in the argument, the variable name should be $DISPLAY, not DISPLAY. In any case, omitting the --display option should just pick the default display. If this problem still matters to you, please see if the applet crashes when started from a console and post a backtrace.

**Comment by flexiondotorg** [comment]
No feedback.
