### ISSUE TITLE
gtk3: gst-mixer window empty and expands down

### ISSUE THREAD

**Issue by infirit** [mate-desktop/mate-media#44]
The following shows up in the log. It also segfaults when I click in the window. I don't yet have debug data in this vm and if a backtrace is needed let me know.

````(mate-volume-control:3175): GLib-GObject-WARNING **: /var/tmp/portage/dev-libs/glib-2.38.2-r1/work/glib-2.38.2/gobject/gsignal.c:2475: signal 'size-request' is invalid for instance '0x188ba40' of type 'GtkScrolledWindow````

**Comment by NiceandGently** [comment]
@infirit 
Does the issue still exists?
I don't see the issue with mate-1.10 gtk3 on baremetal.
