### ISSUE TITLE
manpage out of date for mate-volume-control

### ISSUE THREAD

**Issue by jeisner** [mate-desktop/mate-media#54]
```
OPTIONS
       -p, --page=playback|recording|switches|options
              Launch mate-volume-control on the specified page/tab.
```
These are no longer the tab names.  The second line should be:
```
       -p, --page=effects|hardware|input|output|applications
```

**Comment by monsta** [comment]
It seems that the same manpage is used for both PulseAudio and GStreamer versions of mate-media. The manpage seems to be about GStreamer version (notice also ```--help-gst``` switch there).

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/mate-media/commit/2372c2c62cdbbf4b757eacb086577e197e47e6b2.
