### ISSUE TITLE
volume applet: selected device in preferences not used

### ISSUE THREAD

**Issue by cweiske** [mate-desktop/mate-media#55]
When selecting a different device in the applet preferences, closing and re-opening the preferences show the old device and not the newly selected device. Scrolling on the applet icon also changes the volume of the previous device and not the newly selected one.

![volume control preference](http://fotos.cweiske.de/screenshots/2015-02-24%20mate%20volume%20control%20applett.png)

This is with "Volume Applet 1.8.0" on Ubuntu 14.04.

Note that this was with `mate-media-gstreamer`. With `mate-media-pulse` it works.

**Comment by raveit65** [comment]
Same advise as in
https://github.com/mate-desktop/mate-media/issues/56
