### ISSUE TITLE
mate-volume-control preferences do not work with de_DE.UTF-8

### ISSUE THREAD

**Issue by cweiske** [mate-desktop/mate-media#56]
When opening `mate-volume-control` and clicking "Preferences", no preferences appear.
Instead the terminal shows the following lines:

```
$ mate-volume-control 
** (mate-volume-control:21809): CRITICAL **: gst_alsa_mixer_element_list_tracks: assertion 'this->mixer != NULL' failed
** (mate-volume-control:21809): CRITICAL **: gst_alsa_mixer_element_list_tracks: assertion 'this->mixer != NULL' failed
** (mate-volume-control:21809): CRITICAL **: mate_volume_control_preferences_new: assertion 'GST_IS_MIXER (element)' failed
(mate-volume-control:21809): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(mate-volume-control:21809): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(mate-volume-control:21809): Gtk-CRITICAL **: IA__gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed
```

However, when running it with `LC_ALL=C mate-volume-control`, I can open the preferences.

My default locale settings:
```
$ locale
LANG=de_DE.UTF-8
LANGUAGE=de_DE
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

This happens with `mate-volume-control` on Ubuntu 14.04 with `mate-media-gstreamer` version `1.8.0+dfsg1-3~trusty2`.

**Comment by raveit65** [comment]
I do not see this with mate-1.10.x  in fedora 22 with german locale.
Btw. the gst-mixer is removed after porting to gstreamer-1.0, gstreamer-1.0 do not support this anymore.
Also 1.8 will never get updates from our side anymore after 1.10 is released for several month.
So, in result we can nothing do here.
I suggest to open a downstream report. I never saw this issue with 1.8 in fedora.
Downstream should update to 1.10.
