### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by I-sty** [mate-desktop/mate-media#60]
I am a Arch linux user.
I'm using the Mate DE, but I have a problem:

[isti@istiLaptop ~]$ mate-volume-control
** (mate-volume-control:1251): WARNING **: Connection failed, reconnecting...
** (mate-volume-control:1251): WARNING **: Failed to connect context: Connection refused

**Comment by mratajsky** [comment]
The error you receive means that mate-volume-control wasn't able to connect to a PulseAudio daemon running on your PC.

If you use PulseAudio, make sure that it works correctly.
If you do not use PulseAudio, you may want to install gst-mixer instead, which is an alternative mixer that works with ALSA.

You can also wait for the next MATE release, where the main mixer is able to work with both PulseAudio and ALSA.

**Comment by I-sty** [comment]
Thank you your reply!
I will waiting for the new release.

**Comment by monsta** [comment]
@flexiondotorg: can be closed now I guess

**Comment by flexiondotorg** [comment]
This should be fixed in MATE 1.10
