### ISSUE TITLE
mate-volume-control is difficult to see on Blue Submarine theme (GTK3)

### ISSUE THREAD

**Issue by Mikaela** [mate-desktop/mate-media#66]
![indicators](https://i.imgur.com/8rv3g0o.png)

How many waves are there in the icon (between clipit & network manager) when you are looking from longer distance?
- mate-media-gtk3: 1.10.0-2
- Arch Linux
##

**Comment by raveit65** [comment]
exactly 3.

**Comment by monsta** [comment]
Maybe simply try another icon theme?

**Comment by raveit65** [comment]
This is more an problem with the icon, most icons are designed for a light background.

**Comment by monsta** [comment]
Should we close this as an icon theme issue?

**Comment by raveit65** [comment]
No answer from reporter
