### ISSUE TITLE
The sound theme is lost when we re-open the sound controls window

### ISSUE THREAD

**Issue by Deuchnord** [mate-desktop/mate-media#67]
On Arch Linux, when I set the sound theme in the volume controls window, it is lost after re-opening this window.
I don't know if this happens on the other distributions :-/

**Reproduction:**
1. Open the volume controls window
2. In the first tab, set a sound theme (for instance: _Default_)
3. Close the volume controls window
4. Just for the test, make it play the default sound. For instance, open a terminal and check there is sound when you hint the `Tab` button of your keyboard
5. Re-open the volume controls window: the sound theme has been reset to _No sound_
##

**Comment by direwolfie** [comment]
Have the same issue as mentioned above. But also "Alert volume" in the same tab (Sound effects), if changed, will reset to 0.
Running Linux Mint 17.2 x64 Mate 1.10.2.

**Comment by direwolfie** [comment]
Checked this issue on Debian Jessie x32 MATE 1.8.1. No such problem there.

@Deuchnord It seems that hardly anyone uses system sounds in MATE, he he.. tbh, I only found out about this when I needed to enable notification sounds for Thunderbird.
Are you still having this problem on Arch?

**Comment by Deuchnord** [comment]
Sorry, I completely forgot this issue…

It seems my problem has gone :)

**Comment by raveit65** [comment]
...so we can close the report?

**Comment by raveit65** [comment]
btw. a lot of probs with pulsaudio can solve with disable flat volumes
in /etc/pulse/daemon.conf
```
flat-volumes = no
```

**Comment by Deuchnord** [comment]
> ...so we can close the report?
https://github.com/mate-desktop/mate-media/issues/67#issuecomment-159984182

Yes, we can :)



> btw. a lot of probs with pulsaudio can be solve with disable flat volumes
> in /etc/pulse/daemon.conf
>
>     flat-volumes = no
https://github.com/mate-desktop/mate-media/issues/67#issuecomment-159985047

What does this line do exactly?

**Comment by direwolfie** [comment]
@Deuchnord Here is a good explanation -
Flat-volumes: This is that annoying thing that Windows (and now, PulseAudio, by default) does, where turning up the volume in an application will increase the master system volume alongside it. This has the side-effect that any application which sets its own volume can commandeer the master volume of your system. (Taken from [here] (https://www.reddit.com/r/linux/comments/2rjiaa/horrible_decisions_flat_volumes_in_pulseaudio_a/).)
So it basically disables this "feature".

@raveit65 I did disable flat-volumes on my Debian system (which doesn't have this problem). But thats only because it allowed all media players to control the master volume. I don't understand why would this happen only with "Sound Effects" volume and settings?
Anyway, I'll try this solution tomorrow on the Linux Mint system (don't have it now) and get back to you.

**Comment by raveit65** [comment]
>  I did disable flat-volumes on my Debian system (which doesn't have this problem). But thats only because it allowed all media players to control the master volume. I don't understand why would this happen only with "Sound Effects" volume and settings, and what is controlling it?
Anyway, I'll try this solution tomorrow on the Linux Mint system (don't have it now) and get back to you.

This was more a general hint for better handling pulseaudio ;)
Here on fedora systems i don't have a problem with loading a sound theme.

**Comment by direwolfie** [comment]
> This was more a general hint for better handling pulseaudio ;)
> Here on fedora systems i don't have a problem with loading a sound theme.

Yeah, no idea why Debian would have it enabled by default...
But Linux Mint/Ubuntu has this disabled, and still this is a problem even on a fresh install.

**Comment by direwolfie** [comment]
> Yes, we can :)

@Deuchnord Are you sure that you do not have this problem anymore? I just did a fresh install of Antegros x64 running MATE 1.12.0 on a virtual machine. And it has this problem...

**Comment by Deuchnord** [comment]
@direwolfie really sorry, I confirm I don't have this problem anymore :-/
I didn't do anything, looked like the issue had been solved after an update (probably those which changed the titles of the menu bar)…

**Comment by direwolfie** [comment]
@Deuchnord You are right. I can see that choosing the "Sound theme" got fixed in Arch. But when I move "Alert volume" slider, it gets reset to zero every time.
Please check this if its not too much trouble.

**Comment by Deuchnord** [comment]
I'm sorry @direwolfie, I tested the problem you mentioned, but not having problem :/

**Comment by direwolfie** [comment]
> I'm sorry @direwolfie, I tested the problem you mentioned, but not having problem :/
Understood. Probably got fixed in the future versions and/or versions of dependencies.
