### ISSUE TITLE
MATE Volume Control adjusts volume in highly non-linear way when ALSA backend is used

### ISSUE THREAD

**Issue by LavirtheWhiolet** [mate-desktop/mate-media#70]
I have uninstalled PulseAudio and use plain ALSA. MATE Volume Control has started to behave differently: anything below 50% is inaudible, and all the action occurs between about 70 & 100.

In AlsaMixer the scale is perceived almost linear.

Screenshots show that changing the volume in MATE Volume Control also changes the volume in AlsaMixer. But, as said above, the scale of AlsaMixer is perceived almost linear so the scale in MATE Volume Control is perceived like logarithmic one.

![-1](https://cloud.githubusercontent.com/assets/231566/10831358/1142e3ca-7ea7-11e5-873d-059f32bbbd9d.png)
![-2](https://cloud.githubusercontent.com/assets/231566/10831361/15355fc6-7ea7-11e5-8bae-e77ac3d83dba.png)
![-3](https://cloud.githubusercontent.com/assets/231566/10831365/17eae20e-7ea7-11e5-8d52-695c961a7b6c.png)
![-4](https://cloud.githubusercontent.com/assets/231566/10831369/1a0c554a-7ea7-11e5-8eb7-2e84fe6b2883.png)

**Comment by monsta** [comment]
@mratajsky: can you please take a look at this?

**Comment by mratajsky** [comment]
From the screenshot you are using the gst-mixer from MATE 1.8 which is unsupported software. The current mixer in MATE 1.10 and 1.12 should not exhibit this behaviour (if it does, please let us know), although it's currently lacking in support for secondary channels on ALSA (I hope we'll improve this soon). So in short, please use a more recent mixer.
