### ISSUE TITLE
Volume control : output or input ?

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/mate-media#72]
![capture-preferences du son](https://cloud.githubusercontent.com/assets/3955499/11318756/883091c0-905f-11e5-9b39-81fa5793ab03.png)

Showing the output volume at the top of the window is very strange for a new user. When he tries to parameter the input volume, input and output volume are shown at the same time !

The output volume should be only in the output volume panel and this panel should be showed by default when we open the Volume control applet.

**Comment by Petrouchka** [comment]
Would be better to remove this application and replace it by pavumeter.

**Comment by raveit65** [comment]
What is so difficult to understand that master out is showed in every tab?
Which is very useful if you use several input devices or applications.
And you can use pavu-control inside pn-mixer ( unversal sound tray applet)
So, no need to remove something because of a personal preference.

**Comment by Petrouchka** [comment]
What is so difficult to understand that master out in every tab and master in only in input tab is a nonsense ? Look at pavumeter and you will understand it.
