### ISSUE TITLE
mate-volume-control-applet volume increments

### ISSUE THREAD

**Issue by jmssil** [mate-desktop/mate-media#76]
Hi,

I have reported or seen this reported somewhere but I can't find it any longer:

Many months ago the volume control of mate-volume-control-applet with the mouse wheel stopped using increments/decrements of 5 %. Instead it shows 49 %, 54 %, etc.

Can it be fixed or is there a solution already?

Thanks.
##

**Comment by flexiondotorg** [comment]
This is filed in the wrong project, please file this issue in:

  * https://github.com/mate-desktop/mate-panel

Thanks :-)

**Comment by raveit65** [comment]
@flexiondotorg 
the applet is here https://github.com/mate-desktop/mate-media/blob/master/mate-volume-control/gvc-applet.c
;-)
