### ISSUE TITLE
Not build with gtk 3

### ISSUE THREAD

**Issue by reserge** [mate-desktop/mate-media#80]
I use ArchLinux. Package not build with gtk3 version (gcc 6.1.1, gtk 3.20.8, glib 2.48).

> gvc-stream-status-icon.c:732:39: **error: ‘on_status_icon_activate’ undeclared (first use in this function)
>                            G_CALLBACK (on_status_icon_activate),**
>                                        ^
> /usr/include/glib-2.0/gobject/gsignal.h:475:60: note: in definition of macro ‘g_signal_connect’
>      g_signal_connect_data ((instance), (detailed_signal), (c_handler), (data), NULL, (GConnectFlags) 0)
>                                                             ^~~~~~~~~
> gvc-stream-status-icon.c:732:27: note: in expansion of macro ‘G_CALLBACK’
>                            G_CALLBACK (on_status_icon_activate),
>                            ^~~~~~~~~~
> gvc-stream-status-icon.c:736:39: **error: ‘on_status_icon_button_press’ undeclared (first use in this function)
>                            G_CALLBACK (on_status_icon_button_press),**
>                                        ^
> /usr/include/glib-2.0/gobject/gsignal.h:475:60: note: in definition of macro ‘g_signal_connect’
>      g_signal_connect_data ((instance), (detailed_signal), (c_handler), (data), NULL, (GConnectFlags) 0)
>                                                             ^~~~~~~~~
> gvc-stream-status-icon.c:736:27: note: in expansion of macro ‘G_CALLBACK’
>                            G_CALLBACK (on_status_icon_button_press),
>                            ^~~~~~~~~~
> gvc-stream-status-icon.c:740:39: **error: ‘on_status_icon_popup_menu’ undeclared (first use in this function)
>                            G_CALLBACK (on_status_icon_popup_menu),**
>                                        ^
> /usr/include/glib-2.0/gobject/gsignal.h:475:60: note: in definition of macro ‘g_signal_connect’
>      g_signal_connect_data ((instance), (detailed_signal), (c_handler), (data), NULL, (GConnectFlags) 0)
>                                                             ^~~~~~~~~
> gvc-stream-status-icon.c:740:27: note: in expansion of macro ‘G_CALLBACK’
>                            G_CALLBACK (on_status_icon_popup_menu),
>                            ^~~~~~~~~~
> gvc-stream-status-icon.c:744:39: **error: ‘on_status_icon_scroll_event’ undeclared (first use in this function)
>                            G_CALLBACK (on_status_icon_scroll_event),**
> 
>

**Comment by raveit65** [comment]
I guess you build from master?
Can you please try to use 'autoreconf -fi' + configure --with-gtk=3.0, instead of using autigen.sh ?

**Comment by reserge** [comment]
Thanks for the reply! With 'autoreconf -fi' + configure built successfully.
