### ISSUE TITLE
mate-volume-control-applet volume increments

### ISSUE THREAD

**Issue by jmssil** [mate-desktop/mate-media#83]
Hi,

For about one year, the volume control of mate-volume-control-applet with the mouse wheel stopped using increments/decrements of 5 %. Instead it shows 49 %, 54 %, etc.

Can it be fixed or is there a solution already?

Thanks.

**Comment by flexiondotorg** [comment]
The increment between 49% and 54% is 5%.

**Comment by jmssil** [comment]
Yes, you're right. From 100 % it drops to 94 % and then in 5 % decrements. From 0 % it rises to 4 %, and then in 5 % increments.

**Comment by muesli4** [comment]
I had a look at the code:

1. *GTK* widgets display the floored value. Thus even if the value is 4.998779% the label will show 4%.

2. Floating point addition may produce small errors. That could be the reason for an additional step between 99% and 100%. Or it could be that...

3. The mixer itself only supports integer values and setting it will feed back the truncated value to the slider (or `GtkAdjustment`). (And at least at my machine the maximum value `65536` is not divisible by `5`, so it's not possible to control it in exact 5% steps.)

A solution could be to round (up or down) to 5% (or whatever number is desired) steps whenever the `GtkAdjustment` changes.

**Comment by jmssil** [comment]
This seems a regression since it was working correctly before. And for many years.

**Comment by muesli4** [comment]
@jmssil I don't see any recent commits that changed anything about it. It might be that:

- Another library changed (e.g., *mate mixer*)
- You used a different audio device (with different resolution)

Personally I can't remember not seeing that behavior. My audio device has a resolution of `65536`, thus increasing in 5% steps will result in an increment size of `3276.8`. Setting then eats the `.8` and the signal connection will ship back `old_volume + 3276` (i.e. as powers of two are never divisible by 5 it will not work for those). I see two solutions: Either work only with percentages or add a mechanism that counteracts the effect (*which I already implemented*).

The other part involves showing the volume, which is an imprecise floating point number, with format "%.0f". It's basically printing the integer part of the number. A more reasonable behavior is to round to hundreths of the maximum volume.

If you agree with my solution, I will be happy to provide it as a pull request.

**Comment by jmssil** [comment]
Thanks for you analysis and code, @muesli4.

From the possible culprits you list, I don't know about mate-mixer, but my audio device is the same. And I also notice this in other computers/platforms.

This issue has been reported before, in another component. flexiondotorg told me to move it here, so it is older than its report in mate-volume-control-applet.

The original report: https://github.com/mate-desktop/mate-media/issues/76#issuecomment-273341812

And it seems I had reported it earlier somewhere else.

So this may have almost 2 years. Have you checked the commit logs from that far?

**Comment by muesli4** [comment]
@jmssil You're welcome. I'm using *mate-volume-control-applet* with my patch since then. Somehow I felt bothered by those minor inconsistencies. ;)
I had a look at this repository. However it could have been introduced much earlier (i.e. in GNOME or a previous repository).

**Comment by jmssil** [comment]
OK. I'm not using MATE anymore but I have it installed and can test your solution if needed. Please tell me some action is required from my part. Thanks.

**Comment by monsta** [comment]
Fix is now released in mate-media 1.18.1 (thanks @muesli4).
