### ISSUE TITLE
No volume applet in 1.16?

### ISSUE THREAD

**Issue by nikolas-n** [mate-desktop/mate-media#86]
I just installed Debian Stretch with Mate 1.16 and there isn't an option in Add applets (after clicking on a Panel) for the Volume Control Icon. I can control the volume only through the notification area. In previous installations of Mate I used to have a lot of volume icons in at least the two horizontal panels (each for one screen), so this feature is crucial for my desktop. Am I missing something? Do I have to install something?

**Comment by monsta** [comment]
I don't know how to get "a lot of volume icons". All we have is the volume control app with a tray icon.

**Comment by nikolas-n** [comment]
I might have not been so clear. I am talking about a mixer applet (I'm not sure whether that's its name). So, in previous versions of MATE, you could right click on panel, then select _Add to Panel_ and, afterwards, you got the following:

![2017-05-09 09_47_33-greenshot](https://cloud.githubusercontent.com/assets/5776664/25838613/b4010cde-349c-11e7-92c1-b72ea96bdabd.png)

Then, there was the choice of "Volume Control", which is now absent. Is there a way to enable it?

I was referring to "a lot of volume icons" in the sense that you can add the applet as many times you want in any panel.

**Comment by monsta** [comment]
Maybe it was some third-party applet?

**Comment by nikolas-n** [comment]
I think I found out what it was exactly. It was gst-mixer-applet which was removed since version 1.10. Previous version of Debian (Jessie) had mate 1.8, so it was included, but not anymore. It seems that everyone forgot about that very useful applet. What a pity.

**Comment by monsta** [comment]
Ah, that one. Well, yes, it was removed in 1.10 along with GStreamer support (https://github.com/mate-desktop/mate-media/commit/d1c86461bebd11bab895ee4e7506233947756870).

**Comment by nikolas-n** [comment]
I see. Do you know if there is any alternative to that?

**Comment by monsta** [comment]
There might be some third-party applet, but I'm not aware of it. Someone might also take gst-mixer-applet and adapt it to libmatemixer (the audio library we use since 1.10), but I don't know if it's feasible. The applet was tied to GStreamer, so it was gone with it.
