### ISSUE TITLE
Default autogen breaks build

### ISSUE THREAD

**Issue by genpfault** [mate-desktop/mate-media#91]
#### Expected behaviour
`./autogen.sh && make` should build out-of-the-box

#### Actual behaviour
Default autogen does...something to un-declare `on_status_icon_activate`:

    gvc-stream-status-icon.c:678:39: error: ‘on_status_icon_activate’ undeclared (first use in this function)

#### Steps to reproduce the behaviour

1. Clone
1. Checkout the `v1.18.0` tag
1. `./autogen.sh && make`
1. Observe build failure(s)

Workaround: `./autogen.sh && autoreconf -fi && ./configure && make` as suggested by #80 builds without error.

#### MATE general version
1.18

#### Package version
v1.18.0 (9e4b277b170321bd4a9d3a793089941afeabc3b3)

#### Linux Distribution
Debian Stretch amd64

**Comment by monsta** [comment]
It might be related to weird option that disables the deprecated GTK+ stuff by default... This should be fixed in 1.18.1 (by https://github.com/mate-desktop/mate-media/commit/e6d3887e68181afc634dde19601f4d2f47436b23). Can you try it?

**Comment by genpfault** [comment]
Yup, e6d3887 works on my system, thanks!

**Comment by monsta** [comment]
Ok good :slightly_smiling_face:
