### ISSUE TITLE
Actions not executed when keyboard shortcut have Mod4/Super/Windows key

### ISSUE THREAD

**Issue by allanforever** [mate-desktop/mate-media#92]
#### Expected behaviour
Actions to be executed
(The main menu only shows up when the Mod4/Super/Windows is released, so, if before the release any keyboard shortcut combination matches the keys pressed then that shortcut should be executed instead of displaying the main menu)

#### Actual behaviour
Main menu opened

#### Steps to reproduce the behaviour
Create any keyboard shortcut with the Mod4/Super/Windows key (for example, Volume Mute> Ctrl+Alt+Mod4+Down)
Start the key combination with the Mod4/Super/Windows: whatever order you press the other keys the action is not executed, instead the main menu is shown when the Mod4/Super/Windows is release though

#### MATE general version
MATE Desktop Environment 1.16.1

#### Linux Distribution
Linux Mint 18.1 'Serena' "MATE 64-BIT"

**Comment by raveit65** [comment]
Lets assume that you mean mintmenu ;-)
If you use the super key for another shortcut, you need to use another key for open mintmenu.
You can change that in mintmenu preferences.
For example i use 'super+m' for opening mintmenu.
Not really a bug, imo.
@monsta  thoughts ?

**Comment by monsta** [comment]
https://github.com/linuxmint/mintmenu/issues/98
fixed in 5.7.9 by https://github.com/linuxmint/mintmenu/commit/76ba6daf64885ee9422846a85e61f502c68ed27f, available in Mint 18.2

**Comment by allanforever** [comment]
Thank you so much @monsta, I'll test it when it's officially released :-)
And @raveit65 what i mean is indeed  the mintmenu, but not the shortcut to open it 
In my machine configuration the superkey is the only key to open the mint menu, but the [Sound > Play/Pause] action is triggered with the Ctrl+SuperKey+Alt+ArrowUp combination, and it doesn't work if I start this combination with the SuperKey: if I press SuperKey+Ctrl+Alt+ArrowUp nothing happens with the sound, but when I release this combination the mintmenu pops up, on the other hand if I start the combination with Ctrl or Alt keys the sound is paused/played, understand what i mean?
