### ISSUE TITLE
mate-volume-control-applet — use popover

### ISSUE THREAD

**Issue by TomaszGasior** [mate-desktop/mate-media#95]
If it is possible, use popover for popup window of volume applet such as in Audacious for example.

Please compare.

![compare](https://user-images.githubusercontent.com/1395027/28726877-3e9cc1b6-73c3-11e7-99ae-34cfdfcb31b9.png)

**Comment by raveit65** [comment]
...we don't like the design of popovers, we're not gnome.

**Comment by TomaszGasior** [comment]
I wrote about this for better consistency. GtkVolumeButton uses it. https://developer.gnome.org/gtk3/stable/GtkVolumeButton.html 
Also popovers are designed for purposes like this! ;) And they are good-looking. It is possible to add option in gsettings to enable it? It is very hard to implement this?

**Comment by monsta** [comment]
Hmm... do we use GtkVolumeButton?

**Comment by TomaszGasior** [comment]
It seems to me that no. But it is important for desktop consistence. A lot of apps use GtkVolumeButton with popover. In my opinion MATE developers should notice that their DE is based on GTK3. And GTK3 has its own design concepts — MATE should match these concepts. 

Please understand — I don't say that MATE should replace all menus with hamburger-like popovers and remove all icons from UI. But some parts of MATE should match to all GTK3 world. Now MATE is based on GTK3 — and, in my opinion, it shouldn't live in GTK2 design principles.

**Comment by monsta** [comment]
Hmm GTK+ concepts? Looks more like GNOME concepts that for some reasons are put into a general purpose UI toolkit which is used by lots of other developers, including developers of other desktop environments. There are more examples of this - file open dialog, font chooser dialog, buttons in message dialog...

**Comment by TomaszGasior** [comment]
Ok, I understand. But desktop consistence  is important in my option. So how to solve this? Should we create fork of GTK3 to make it less "gnoomish"? Or should we keep inconsistent interface?
